# Generated by Django 3.2.4 on 2021-06-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('guild_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.guild')),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedWarning',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('red_votes', models.IntegerField(default=0)),
                ('green_votes', models.IntegerField(default=0)),
                ('message_content', models.CharField(default='', max_length=2000)),
                ('moderation_log_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.moderationlog')),
            ],
        ),
    ]
