# Generated by Django 2.2.17 on 2021-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(unique=True)),
                ('red_votes', models.IntegerField(default=0)),
                ('green_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
