# Generated by Django 2.2.17 on 2021-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedwarning',
            name='message_content',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
